# Generated by Django 3.1.7 on 2021-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catch_images/'),
        ),
    ]
