# Generated by Django 3.1.7 on 2021-05-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='num_of_fish',
        ),
        migrations.AlterField(
            model_name='catch',
            name='fish_type',
            field=models.CharField(choices=[('Ponty', 'Ponty'), ('Amur', 'Amur'), ('Keszeg', 'Keszeg'), ('Kárász', 'Kárász'), ('Harcsa', 'Harcsa'), ('Tok', 'Tok')], default='Carp', max_length=50, verbose_name='Fish Type'),
        ),
    ]
