# Generated by Django 3.1.7 on 2021-06-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_trip', '0002_auto_20210520_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='image',
            field=models.ImageField(blank=True, default='deafult_catch_img.jpg', null=True, upload_to='catch_images/'),
        ),
    ]
