# Generated by Django 3.1.7 on 2021-06-17 15:48

from django.db import migrations

def set_default_values(apps, schema_editor):
    Catch = apps.get_model("new_trip", "Catch")
    Catch.objects.filter(image='').update(image="deafult_catch_img.jpg")

class Migration(migrations.Migration):

    dependencies = [
        ('new_trip', '0003_auto_20210617_0919'),
    ]

    operations = [
        migrations.RunPython(set_default_values),
    ]
