# Generated by Django 3.1.7 on 2021-06-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_trip', '0004_auto_20210617_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='image',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to='catch_images/'),
        ),
    ]
