# Generated by Django 3.1.7 on 2021-06-18 08:38

from django.db import migrations

def default_img(apps, schema_editor):
    Catch = apps.get_model("new_trip", "Catch")
    Catch.objects.filter(image='deafult_catch_img.jpg').update(image="default_img.png")

class Migration(migrations.Migration):

    dependencies = [
        ('new_trip', '0005_auto_20210618_1035'),
    ]

    operations = [
        migrations.RunPython(default_img, reverse_code=migrations.RunPython.noop), # reverse_code... migration can be reversed
    ]
