# Generated by Django 3.1.7 on 2021-06-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_trip', '0006_auto_20210618_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catch',
            name='hook_bait',
        ),
        migrations.AddField(
            model_name='catch',
            name='hookbait_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='HookBait'),
        ),
        migrations.CreateModel(
            name='HookBait',
            fields=[
                ('hookbait_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='HookBait')),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_trip.fisherman')),
            ],
            options={
                'verbose_name': 'Hookbait',
                'verbose_name_plural': 'Hookbaits',
            },
        ),
        migrations.AddField(
            model_name='catch',
            name='hookbait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_trip.hookbait'),
        ),
    ]
