# Generated by Django 3.1.7 on 2021-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_trip', '0007_auto_20210629_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='hookbait_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Csali megnevezése'),
        ),
    ]
