# Generated by Django 3.1.7 on 2021-07-13 08:30

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('new_trip', '0007_auto_20210629_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='hookbait_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Csali megnevezése'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default_img.png', force_format='JPEG', keep_meta=True, null=True, quality=95, size=[1080, 1080], upload_to='catch_images/'),
        ),
    ]
